export const fieldDisplayNames = {
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  age: "Age",
  birthdate: "Birth Date",
  gender: "Gender",
  civilStatus: "Civil Status",
  birthRegion: "Birth Region",
  birthProvince: "Birth Province",
  birthCity: "Birth City",
  validIdType: "Valid ID Type",
  otherValidId: "Other Valid ID",
  validIdNumber: "Valid ID Number",
  companyNameId: "Company Name on ID",
  companyName: "Company Name",
  purpose: "Purpose",
  otherPurpose: "Other Purpose",
  medication: "Medication",
  medicationYes: "If Yes, Please Specify",
  alcohol: "Alcohol",
  region: "Region",
  province: "Province",
  city: "City",
  barangay: "Barangay",
  signature: "Signature",
};
